spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  application:
    name: springboot2
default:
  sender:
  recipient:

jwt:
  secret: SequenciaDeCaracteresParaAssinarToken
  expiration: 86400000

aws:
  access_key_id:
  secret_access_key:
s3:
  bucket: curso-spring-ionic
  region: sa-east-1

img:
  prefix:
    client:
      profile: cp
  profile:
    size: 200
logging:
  file:
    name: /opt/dev/logs/springboot2-elk.log
